### ISSUE TITLE
Store file in s3

### ISSUE THREAD

**Issue by zeecher** [xis/baraka#10]
How to store file in s3?

**Comment by xis** [comment]
Hi, baraka currently does not have a shortcut implementation for uploading files to s3 but you can do it with additional library for uploading files to s3 like,
https://docs.aws.amazon.com/sdk-for-go/api/service/s3/

for example let's get the form named `files`
```go
// get the form
files, err := request.GetForm("files") // get the files here
if err != nil {
	fmt.Println(err)
}
```
`files[0].Content` will give you the bytes of the first file in the form, you can pass this bytes to the s3 library.

**Comment by zeecher** [comment]
Hi, thanks for the prompt response, I will try it.
